name: Lint

on:
 # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - '..'
          - eslint-config-airbnb
          - eslint-config-airbnb-base
    defaults:
      run:
        working-directory: "src/${{ matrix.package }}"


  steps:
        name: Run linters
      - uses: actions/checkout@v2
      - uses: wearerequired/lint-action@v2
        name: 'nvm install lts/* && npm install'
        with:
          node-version: 'lts/*'
      - run: npm run lint

    # steps:
    #   - name: Check out Git repository
    #   - uses: actions/checkout@v2

    #   - name: Set up Node.js
    #   - uses: actions/setup-node@v1
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #       run: npm ci

    #   - name: Run linters
    #   - uses: wearerequired/lint-action@v2
    #     run: npm run lint

