name: Lint

on:
 # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci
      - name: ESLint
        run: npm run lint
      - name: ESLint fix
        run: npm run lint:fix
      - name: Setting Github user.email
        run: git config --global user.email "9991571155i@gmail.com"
      - name: Setting Github user.name
        run: git config --global user.name "Ilia Filimonov"
      - name: Adding fixes for committing
        run: git add .
      - name: Committing ESLint fixes
        run: git commit -m "fixed ESLint issues"
      - name: Pushing fixes to current PR branch
        run: git push
      - name: tests
        run: npm test