name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        npm ci

    - name: Lint with ESLint
      run: |
        npx eslint . --ext .js,.jsx,.ts,.tsx --config node_modules/eslint-config-airbnb/index.js
        # Add a flag for fixing the linting errors automatically if desired:
        # npx eslint . --ext .js,.jsx,.ts,.tsx --config node_modules/eslint-config-airbnb/index.js --fix
      env:
        CI: true
